BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "aluno" (
	"alunoID"	INTEGER NOT NULL UNIQUE,
	"nome"	TEXT NOT NULL,
	"email"	TEXT,
	"endereço"	TEXT NOT NULL,
	PRIMARY KEY("alunoID" AUTOINCREMENT)
);
COMMIT;
